version: "3"
services:
  db:
    container_name: price-comparison-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  builder:
    container_name: api-builder
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: builder
    depends_on:
      - db
  distroless:
    container_name: api-distroless
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: production
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      - builder
      - db
